import os

DISCORD_TOKEN = os.environ.get("DISCORD_TOKEN", "")
CHANNEL_ID    = int(os.environ.get("CHANNEL_ID", "0"))

WATCHLIST_STOCKS = [
    "AAPL", "NVDA", "MSFT", "TSLA", "AMZN",
    "META", "GOOGL", "JPM", "NFLX", "AMD",
    "MC.PA", "TTE.PA", "AI.PA", "SAN.PA", "BNP.PA",
]

WATCHLIST_CRYPTO = [
    "BTC-USD", "ETH-USD", "BNB-USD", "SOL-USD",
    "XRP-USD", "ADA-USD", "DOGE-USD", "AVAX-USD",
    "DOT-USD", "XLM-USD", "ATOM-USD", "TRX-USD",
    "SHIB-USD","AAVE-USD", "LTC-USD", "MATIC-USD"
    "LINK-USD"
]

SCAN_INTERVAL_MINUTES = 60
MIN_CONFIDENCE = 70
LOOKBACK_DAYS = "6mo"
